ConectArte/ConectArte/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib import admin
from django.urls import include, path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from apps.vacantes.views import *
from .views import HomeView, home
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', HomeView.as_view(), name = 'home'),
    path('', home),
    path('accounts/', include('allauth.urls')),
    path('users/', include('apps.Usuarios.urls', namespace ="users")),
    path('search/', include('apps.Buscador.urls', namespace='search')),
    path('publicacion/', include('apps.publicaciones.urls', namespace='publicacion')),
    path('vacantes/', VacanteView.as_view(), name="vacante"),
    path('dm/', include('apps.DM.urls', namespace='dm')),
    
]

urlpatterns += staticfiles_urlpatterns()
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ConectArte/apps/DM/urls.py
from django.urls import path
from apps.DM.views import *
app_name ="DM"

urlpatterns = [
    path("<str:username>", mensajes_privados),
    path("ms/<str:username>", DetailMs.as_view(), name="detailms"),
    path("inbox/", Inbox.as_view(), name="inbox"),
]

ConectArte/apps/Usuarios/urls.py
from django.urls import path 
from .views import *
app_name ="Usuarios"

urlpatterns = [
    path("<username>/",ProfileView.as_view(), name="perfil"),
    path("portfolio/<username>",PortfolioView.as_view(), name="portfolio"),
    path('profile/edit', EditProfile, name="editProfile"),

    #Se creó el nuevo path de followers, y de follow y unfollow
    path('profile/followers', followers, name="followers"),    
    path('follow/<str:username>/', follow, name="follow"),
    path('unfollow/<str:username>/', unfollow, name="unfollow"),
]

ConectArte/apps/vacantes/urls.py
from django.urls import path 
from .views import VacanteView
app_name ="vacantes"

urlpatterns = [
    path("MostrarVacantes/",VacanteView.as_view(), name="vacante"),
    
]
## URLS DE VACANTES

ConectArte/apps/DM/models.py
from django.db import models
from django.conf import settings
from apps.Usuarios.models import *

import uuid
from django.apps import apps
from django.db.models import Count

User = settings.AUTH_USER_MODEL

class ModelBase(models.Model):
	id = models.UUIDField(default=uuid.uuid4, primary_key=True, db_index=True, editable=False)
	tiempo = models.DateTimeField(auto_now_add=True)
	actualizar = models.DateTimeField(auto_now=True)

	class Meta:
		abstract = True


class CanalMensaje(ModelBase):
	canal   = models.ForeignKey("Canal", on_delete=models.CASCADE)
	usuario = models.ForeignKey(User, on_delete=models.CASCADE)
	texto =  models.TextField()

class CanalUsuario(ModelBase):
	canal  = models.ForeignKey("Canal", null=True, on_delete=models.SET_NULL)
	usuario = models.ForeignKey(User, on_delete=models.CASCADE)


class CanalQuerySet(models.QuerySet):

	def solo_uno(self):
		return self.annotate(num_usuarios=Count("usuarios")).filter(num_usuarios=1)

	def solo_dos(self):
		return self.annotate(num_usuarios= Count("usuarios")).filter(num_usuarios=2)

	def filtrar_por_username(self, username):
		return self.filter(canalusuario__usuario__username=username)


class CanalManager(models.Manager):
	
	def get_queryset(self, *args, **kwargs):
		return CanalQuerySet(self.model, using=self._db)

	def filtrar_ms_por_privado(self, username_a, username_b):
		return self.get_queryset().solo_dos().filtrar_por_username(username_a).filtrar_por_username(username_b)

	def obtener_o_crear_canal_usuario_actual(self, user):
		qs = self.get_queryset().solo_uno().filtrar_por_username(user.username)
		if qs.exists():
			return qs.order_by("tiempo").first, False

		canal_obj = Canal.objects.create()
		CanalUsuario.objects.create(usuario=user, canal=canal_obj)
		return canal_obj, True

	def obtener_o_crear_canal_ms(self, username_a, username_b):
		qs = self.filtrar_ms_por_privado(username_a, username_b)
		if qs.exists():
			return qs.order_by("tiempo").first(), False #obj, created

		obj_canal =Canal.objects.create()
		canal_usuario_a = CanalUsuario(usuario=username_a, canal=obj_canal)
		canal_usuario_b = CanalUsuario(usuario=username_b, canal=obj_canal)
		CanalUsuario.objects.bulk_create([canal_usuario_a, canal_usuario_b])
		return obj_canal, True

class Canal(ModelBase):

	usuarios = models.ManyToManyField(User, blank=True, through=CanalUsuario)
	objects = CanalManager()

ConectArte/apps/vacantes/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model
from apps.Usuarios.models import *

User = get_user_model()

def user_directory_path(instance, fileName):
    return 'Usuarios/publicaciones/{0}'.format(fileName)
# Create your models here.
class CategoriasVacantes(models.Model):
    IdCategoriaVacante = models.AutoField(primary_key=True)
    CategoriaVacante = models.CharField(max_length=100, null=False, verbose_name="Categoría de la vacante")
    def __str__(self):
        return self.CategoriaVacante



class Vacante(models.Model):
    IdVacante = models.AutoField(primary_key=True)
    CategoriaVacante = models.ForeignKey(CategoriasVacantes, on_delete=models.CASCADE, related_name="autor_vacante")
    AutorVacante = models.ForeignKey(User, on_delete=models.CASCADE, related_name="autor_vacante")
    TituloVacante = models.CharField(max_length=30, blank=False, null=False,  verbose_name="Titulo_Vacante")
    Pago = models.FloatField(null=True, blank=True, verbose_name="Pago")
    DescripcionVacante = models.TextField(blank=False, null=False,  verbose_name="Descripción de la vacante")
    FechaPublicacionVacante = models.DateField(default=timezone.now)

ConectArte/apps/DM/forms.py
from django import forms

class FormMensajes(forms.Form):
	mensaje = forms.CharField(widget=forms.Textarea(attrs = {

			"class": "formulario_ms",
			"placeholder":"Escribe tu mensaje"

		}))

ConectArte/apps/vacantes/forms.py
from django import forms 
from .models import *

class VacanteForm(forms.ModelForm):
    
    DescripcionVacante = forms.CharField(widget=forms.Textarea(attrs={
            'class':"form-control", 'id':"exampleFormControlTextarea1",
            'rows': '6',
            'placeholder': 'Describe el trabajo a realizar:'
            }),
        required=True)
    TituloVacante = forms.CharField(widget=forms.Textarea(attrs={
            'class':"form-control", 'id':"exampleFormControlTextarea1",
            'rows': '1',
            'placeholder': 'Titulo de la vacante:'
            }),
        required=True)

    class Meta:
        model = Vacante 
        fields = ['CategoriaVacante','DescripcionVacante', 'Pago']

ConectArte/apps/vacantes/views.py
from django.views.generic import TemplateView, View
from django.shortcuts import redirect, render, get_object_or_404
from django.core.paginator import Paginator
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.db.models import Q
from apps.Usuarios.models import Usuario
from .forms import *
from apps.DM.models import *
from .models import *

def is_valid_param(param):
        return param != '' and param is not None

class VacanteView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        inbox = Canal.objects.filter(canalusuario__usuario__in=[request.user.id])
        form = VacanteForm()
        Vacantes = Vacante.objects.all()

        cantante_cb = request.GET.get('cantante_cb')
        musico_cb = request.GET.get('musico_cb')
        animador_cb = request.GET.get('animador_cb')
        pintor_cb = request.GET.get('pintor_cb')
        artesano_cb = request.GET.get('artesano_cb')
        fotografo_cb = request.GET.get('fotografo_cb')
        escritor_cb = request.GET.get('escritor_cb')
        
        max_num = request.GET.get('filtro_maximo')
        min_num = request.GET.get('filtro_minimo')

        if is_valid_param(min_num):
            Vacantes = Vacantes.filter(Pago__gte=min_num)

        if is_valid_param(max_num):
            Vacantes = Vacantes.filter(Pago__lt=max_num)

        if cantante_cb == 'on' and musico_cb == 'on' and animador_cb == 'on' and pintor_cb == 'on' and artesano_cb == 'on' and fotografo_cb == 'on' and escritor_cb == 'on':
            Vacantes = Vacantes.filter(Q(CategoriaVacante_id=1)|Q(CategoriaVacante_id=2)|Q(CategoriaVacante_id=3)|Q(CategoriaVacante_id=4)|Q(CategoriaVacante_id=5)|Q(CategoriaVacante_id=6)|Q(CategoriaVacante_id=7))

        elif cantante_cb == 'on' and musico_cb == 'on' and animador_cb == 'on' and pintor_cb == 'on' and artesano_cb == 'on' and fotografo_cb == 'on':
            Vacantes = Vacantes.filter(Q(CategoriaVacante_id=1)|Q(CategoriaVacante_id=2)|Q(CategoriaVacante_id=3)|Q(CategoriaVacante_id=4)|Q(CategoriaVacante_id=5)|Q(CategoriaVacante_id=6))
        
        elif cantante_cb == 'on' and musico_cb == 'on' and animador_cb == 'on' and pintor_cb == 'on' and artesano_cb == 'on' and escritor_cb == 'on':
            Vacantes = Vacantes.filter(Q(CategoriaVacante_id=1)|Q(CategoriaVacante_id=2)|Q(CategoriaVacante_id=3)|Q(CategoriaVacante_id=4)|Q(CategoriaVacante_id=5)|Q(CategoriaVacante_id=7))
        
        elif cantante_cb == 'on' and musico_cb == 'on' and animador_cb == 'on' and pintor_cb == 'on' and fotografo_cb == 'on' and escritor_cb == 'on':
            Vacantes = Vacantes.filter(Q(CategoriaVacante_id=1)|Q(CategoriaVacante_id=2)|Q(CategoriaVacante_id=3)|Q(CategoriaVacante_id=4)|Q(CategoriaVacante_id=6)|Q(CategoriaVacante_id=7))

        elif cantante_cb == 'on' and musico_cb == 'on' and animador_cb == 'on' and artesano_cb == 'on' and fotografo_cb == 'on' and escritor_cb == 'on':
            Vacantes = Vacantes.filter(Q(CategoriaVacante_id=1)|Q(CategoriaVacante_id=2)|Q(CategoriaVacante_id=3)|Q(CategoriaVacante_id=5)|Q(CategoriaVacante_id=6)|Q(CategoriaVacante_id=7))

        elif cantante_cb == 'on' and musico_cb == 'on' and pintor_cb == 'on' and artesano_cb == 'on' and fotografo_cb == 'on' and escritor_cb == 'on':
            Vacantes = Vacantes.filter(Q(CategoriaVacante_id=1)|Q(CategoriaVacante_id=2)|Q(CategoriaVacante_id=4)|Q(CategoriaVacante_id=5)|Q(CategoriaVacante_id=6)|Q(CategoriaVacante_id=7))

        elif cantante_cb == 'on' and animador_cb == 'on' and pintor_cb == 'on' and artesano_cb == 'on' and fotografo_cb == 'on' and escritor_cb == 'on':
            Vacantes = Vacantes.filter(Q(CategoriaVacante_id=1)|Q(CategoriaVacante_id=3)|Q(CategoriaVacante_id=4)|Q(CategoriaVacante_id=5)|Q(CategoriaVacante_id=6)|Q(CategoriaVacante_id=7))

        elif musico_cb == 'on' and animador_cb == 'on' and pintor_cb == 'on' and artesano_cb == 'on' and fotografo_cb == 'on' and escritor_cb == 'on':
            Vacantes = Vacantes.filter(Q(CategoriaVacante_id=2)|Q(CategoriaVacante_id=3)|Q(CategoriaVacante_id=4)|Q(CategoriaVacante_id=5)|Q(CategoriaVacante_id=6)|Q(CategoriaVacante_id=7))

        elif cantante_cb == 'on' and musico_cb == 'on' and animador_cb == 'on' and pintor_cb == 'on' and artesano_cb == 'on':
                    Vacantes = Vacantes.filter(Q(CategoriaVacante_id=1)|Q(CategoriaVacante_id=2)|Q(CategoriaVacante_id=3)|Q(CategoriaVacante_id=4)|Q(CategoriaVacante_id=5))

        elif cantante_cb == 'on' and musico_cb == 'on' and animador_cb == 'on' and pintor_cb == 'on' and fotografo_cb == 'on':
                    Vacantes = Vacantes.filter(Q(CategoriaVacante_id=1)|Q(CategoriaVacante_id=2)|Q(CategoriaVacante_id=3)|Q(CategoriaVacante_id=4)|Q(CategoriaVacante_id=6))
        
        elif cantante_cb == 'on' and musico_cb == 'on' and animador_cb == 'on' and pintor_cb == 'on' and escritor_cb == 'on':
                    Vacantes = Vacantes.filter(Q(CategoriaVacante_id=1)|Q(CategoriaVacante_id=2)|Q(CategoriaVacante_id=3)|Q(CategoriaVacante_id=4)|Q(CategoriaVacante_id=7))

        elif cantante_cb == 'on' and musico_cb == 'on' and animador_cb == 'on':
                    Vacantes = Vacantes.filter(Q(CategoriaVacante_id=1)|Q(CategoriaVacante_id=2)|Q(CategoriaVacante_id=3)) 

        elif cantante_cb == 'on' and musico_cb == 'on' and pintor_cb == 'on':
                    Vacantes = Vacantes.filter(Q(CategoriaVacante_id=1)|Q(CategoriaVacante_id=2)|Q(CategoriaVacante_id=4)) 

        elif cantante_cb == 'on' and musico_cb == 'on' and artesano_cb == 'on':
                    Vacantes = Vacantes.filter(Q(CategoriaVacante_id=1)|Q(CategoriaVacante_id=2)|Q(CategoriaVacante_id=5))

        elif cantante_cb == 'on' and musico_cb == 'on' and fotografo_cb == 'on':
                    Vacantes = Vacantes.filter(Q(CategoriaVacante_id=1)|Q(CategoriaVacante_id=2)|Q(CategoriaVacante_id=6))

        elif cantante_cb == 'on' and musico_cb == 'on' and escritor_cb == 'on':
                    Vacantes = Vacantes.filter(Q(CategoriaVacante_id=1)|Q(CategoriaVacante_id=2)|Q(CategoriaVacante_id=7))

        elif cantante_cb == 'on' and animador_cb == 'on' and pintor_cb == 'on':
                    Vacantes = Vacantes.filter(Q(CategoriaVacante_id=1)|Q(CategoriaVacante_id=3)|Q(CategoriaVacante_id=4))
            
        elif cantante_cb == 'on' and animador_cb == 'on' and artesano_cb == 'on':
                    Vacantes = Vacantes.filter(Q(CategoriaVacante_id=1)|Q(CategoriaVacante_id=3)|Q(CategoriaVacante_id=5))

        elif cantante_cb == 'on' and animador_cb == 'on' and fotografo_cb == 'on':
                    Vacantes = Vacantes.filter(Q(CategoriaVacante_id=1)|Q(CategoriaVacante_id=3)|Q(CategoriaVacante_id=6))

        elif cantante_cb == 'on' and animador_cb == 'on' and escritor_cb == 'on':
                    Vacantes = Vacantes.filter(Q(CategoriaVacante_id=1)|Q(CategoriaVacante_id=3)|Q(CategoriaVacante_id=7))

        elif cantante_cb == 'on' and pintor_cb == 'on' and artesano_cb == 'on':
                    Vacantes = Vacantes.filter(Q(CategoriaVacante_id=1)|Q(CategoriaVacante_id=4)|Q(CategoriaVacante_id=5))
            
        elif cantante_cb == 'on' and pintor_cb == 'on' and fotografo_cb == 'on':
                    Vacantes = Vacantes.filter(Q(CategoriaVacante_id=1)|Q(CategoriaVacante_id=4)|Q(CategoriaVacante_id=6))

        elif cantante_cb == 'on' and pintor_cb == 'on' and escritor_cb == 'on':
                    Vacantes = Vacantes.filter(Q(CategoriaVacante_id=1)|Q(CategoriaVacante_id=4)|Q(CategoriaVacante_id=7))

        elif cantante_cb == 'on' and artesano_cb == 'on' and fotografo_cb == 'on':
                    Vacantes = Vacantes.filter(Q(CategoriaVacante_id=1)|Q(CategoriaVacante_id=5)|Q(CategoriaVacante_id=6))

        elif cantante_cb == 'on' and artesano_cb == 'on' and escritor_cb == 'on':
                    Vacantes = Vacantes.filter(Q(CategoriaVacante_id=1)|Q(CategoriaVacante_id=5)|Q(CategoriaVacante_id=7))

        elif cantante_cb == 'on' and fotografo_cb == 'on' and escritor_cb == 'on':
                    Vacantes = Vacantes.filter(Q(CategoriaVacante_id=1)|Q(CategoriaVacante_id=6)|Q(CategoriaVacante_id=7))

        elif musico_cb == 'on' and animador_cb == 'on' and pintor_cb == 'on':
                    Vacantes = Vacantes.filter(Q(CategoriaVacante_id=2)|Q(CategoriaVacante_id=3)|Q(CategoriaVacante_id=4)) 

        elif musico_cb == 'on' and animador_cb == 'on' and artesano_cb == 'on':
                    Vacantes = Vacantes.filter(Q(CategoriaVacante_id=2)|Q(CategoriaVacante_id=3)|Q(CategoriaVacante_id=5)) 

        elif musico_cb == 'on' and animador_cb == 'on' and fotografo_cb == 'on':
                    Vacantes = Vacantes.filter(Q(CategoriaVacante_id=2)|Q(CategoriaVacante_id=3)|Q(CategoriaVacante_id=6))

        elif musico_cb == 'on' and animador_cb == 'on' and escritor_cb == 'on':
                    Vacantes = Vacantes.filter(Q(CategoriaVacante_id=2)|Q(CategoriaVacante_id=3)|Q(CategoriaVacante_id=7))

        elif musico_cb == 'on' and pintor_cb == 'on' and artesano_cb == 'on':
                    Vacantes = Vacantes.filter(Q(CategoriaVacante_id=2)|Q(CategoriaVacante_id=4)|Q(CategoriaVacante_id=5))

        elif musico_cb == 'on' and pintor_cb == 'on' and fotografo_cb == 'on':
                    Vacantes = Vacantes.filter(Q(CategoriaVacante_id=2)|Q(CategoriaVacante_id=4)|Q(CategoriaVacante_id=6))
            
        elif musico_cb == 'on' and pintor_cb == 'on' and escritor_cb == 'on':
                    Vacantes = Vacantes.filter(Q(CategoriaVacante_id=2)|Q(CategoriaVacante_id=4)|Q(CategoriaVacante_id=7))

        elif musico_cb == 'on' and artesano_cb == 'on' and fotografo_cb == 'on':
                    Vacantes = Vacantes.filter(Q(CategoriaVacante_id=2)|Q(CategoriaVacante_id=5)|Q(CategoriaVacante_id=6))

        elif musico_cb == 'on' and artesano_cb == 'on' and escritor_cb == 'on':

ConectArte/templates/pages/canal_detail.html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
  integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
  integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
  integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
  integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<link rel="stylesheet" href="static\css\styles.css">

{% extends 'base.html' %}
{% load static %}

{% block navbar %}
{% include 'components/navbar.html' %}
{% endblock navbar %}

{% block left_sidebar %}
{% include 'components/sidebars/leftBar/sidebar.html' %}

{% endblock left_sidebar %}
{% block content %}
	
<style>
		
	#contenedor_ms{
		width: 100%;
		height: calc(70vh);
		margin: 5px 0;
		overflow-y: auto;
		border-bottom: 1px solid #e6e6e6;
		background: #fff;
	}

	.div_ms{
		margin: 1.2rem auto;
		width: 35%;
		padding: 0.2rem 0.6rem 02rem 0.6rem;

	}
	.mis_mensajes{
		margin-right: 5px;
		background-color:rgb(29, 161, 242);
		color: #fff;
		border-bottom-left-radius: 16px;
		border-top-left-radius: 16px;
		border-top-right-radius: 16px;
		height: 73px; 
        width: 34%;
	}

	.tus_mensajes{
		background: rgb(230, 236, 240);
		margin-left: 5px;
		border-bottom-right-radius: 16px;
		border-top-left-radius: 16px;
		border-top-right-radius: 16px;
		height: 73px; 
        width: 34%;

	}

	.div_form_ms{
		width: 100%;
		margin-top: 5px;
		margin-bottom: 5px;
		margin-left: -3px;
		border:1px solid #e6e6e6;
	}

	#id_mensaje{
		display: block;
		padding: 6px 12px;
		margin-left: 1%;
		margin-right: 1%;
		width: 98%;
		min-width: 98%;
		max-width: 98%;
		height: 70px;
		min-height: 70px;
		max-height: 70px;
		box-sizing: border-box;
		font-size: 14px;
		color: #333;
		border:1px solid #ccc;
		border-radius: 4px;

	}

	.btn_enviar{
		background: rgb(29, 161, 242);
		color: #fff;
		padding: 5px 10px;
		font-weight: 600;
		border-radius: 5px;
		border:none;
		outline: none;
		border-bottom: 5px solid rgb(29, 161, 242);
		width: 150px;
		cursor: pointer;
		display: block;
		margin: 10px auto;
		font-size: 15px;
		transition: 0.3;
		
	}

</style>


	<!--<h3>Identificador del canal: {{object.id}}</h3> -->

	<div style="display: flex; height: 55px;">
		<div style="width: 55px; height: 50px;">
		  <img style="border-radius: 50%;width: 45px; height: 45px; margin-left: 2%; margin-top: 20%;" src="{% static 'images/sin-foto.png' %}" alt="art">
		</div>
		<p style="margin-left: 2px; margin-top: 3%; font-weight: 600;font-size: 20px;">Chat {{second_user.usuario}}</p>
	</div>

	<div id="contenedor_ms">
	{% for mensaje in object.canalmensaje_set.all %}	
		<div class="div_ms 
		{% if request.user == mensaje.usuario %}
		mis_mensajes
		{% else %} 
		tus_mensajes
		{% endif %}">
			
			<h2 style="text-align: center; font-weight: 700;font-size: 13px;" class="modal-title"
            id="exampleModalLabel"> {{mensaje.usuario}}</h2>
			
			<h2 style=" font-size: 15px;margin-top: 4%;" class="modal-title"
            id="exampleModalLabel">{{mensaje.texto}}</h2>
			
			<h3 style="text-align: center; margin-top: 3%;font-weight: 650;font-size: 11px;" class="modal-title"
            id="exampleModalLabel">{{mensaje.tiempo}}</h3>
		</div>

	{% endfor %}
	</div>
	
	<div class="div_form_ms">
		<form id="form_submit" action="{{ request.path }}" method="POST">
			{% csrf_token %}

			{{form.as_p}}
			
			<button type="submit" class="btn_enviar">
				Enviar
			</button>

		</form>

	</div>

<script>

	const MsgForm = document.getElementById("form_submit")
	const msgContainer = document.getElementById("contenedor_ms")


	MsgForm.addEventListener("submit", (event) => {

		event.preventDefault()

		const  targetDate = event.target 
		const formData = new FormData(targetDate)

		const xhr = new XMLHttpRequest() 

		const endpoint = MsgForm.getAttribute("action")
		const method = MsgForm.getAttribute("method")
		xhr.open(method, endpoint)

		xhr.responseType = 'json'

		xhr.setRequestHeader("HTTP_X_REQUESTED_WITH", "XMLHttpRequest")
		xhr.setRequestHeader("X-Requested-With", "XMLHttpRequest")

		xhr.onload = () =>{

			console.log(xhr.status, xhr.response)

			if(xhr.status === 201){
				const respuestaData = xhr.response
				let actualMensajeHtml = msgContainer.innerHTML
				actualMensajeHtml += `<div class=''><b>${respuestaData.username}</b><p>${respuestaData.mensaje}</p></div>` 
				msgContainer.innerHTML = actualMensajeHtml
				MsgForm.reset()
			}else if(xhr.status === 400){
				console.log(hxr.response)
			}else{
				alert("Un error ocurrio, por favor trata luego")
			}

		}

		xhr.send(formData)


	})
	


</script>

{% endblock %}

ConectArte/templates/pages/inbox.html
{% block contenedor %}

<h1>
	Bienvenido {{user}}
</h1>



{% for inbox in inbox %}
<div class="div_inbox">

	
	{% for second_user in inbox.canalusuario_set.all %}

		{% if second_user.usuario ==  request.user %}

		{% else %}

			<a href="{% url 'dm:detailms' second_user.usuario.username %}">
				<p>
					{{second_user.usuario}}
				</p>
				<small>
					({{inbox.canalmensaje_set.count}}) Mensajes
				</small>
			</a>

		{% endif %}

	{% endfor %}

	{% if inbox.canalmensaje_set.count != 0 %}
		<div class="div_ms_inbox">
			
			{% with ultimo_mensaje=inbox.canalmensaje_set.last %}

				<p>
					Mensaje: {{ultimo_mensaje.texto}}
				</p>

			{% endwith %}
		</div>	
	{% else %}
		<p>
			No hay mensajes en nuestro inbox
		</p>
	{% endif %}



</div>
{% empty %}

<h2>
	Inbox Vacio
</h2>

{% endfor %}


<style>
	
	.div_inbox{
		width: 90%;
		margin:10px auto;
		background: #fff;
		border-radius: 5px;
		border:1px solid #e6e6e6;
		padding: 5px;
	}

</style>
		
{% endblock %}