ConectArte/ConectArte/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib import admin
from django.urls import include, path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from apps.vacantes.views import *
from .views import HomeView, home
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', HomeView.as_view(), name = 'home'),
    path('', home),
    path('accounts/', include('allauth.urls')),
    path('users/', include('apps.Usuarios.urls', namespace ="users")),
    path('search/', include('apps.Buscador.urls', namespace='search')),
    path('publicacion/', include('apps.publicaciones.urls', namespace='publicacion')),
    path('vacantes/', VacanteView.as_view(), name="vacante"),
    path('dm/', include('apps.DM.urls', namespace='dm')),
    
]

urlpatterns += staticfiles_urlpatterns()
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ConectArte/apps/Buscador/urls.py
from django.urls import path 
from .views import SearchArtist
app_name ="Buscador"

urlpatterns = [
    path("search/",SearchArtist.as_view(), name="searchProfile"),
]

ConectArte/apps/DM/urls.py
from django.urls import path
from apps.DM.views import *
app_name ="DM"

urlpatterns = [
    path("<str:username>", mensajes_privados),
    path("ms/<str:username>", DetailMs.as_view(), name="detailms"),
    path("inbox/", Inbox.as_view(), name="inbox"),
]

ConectArte/apps/Usuarios/urls.py
from django.urls import path 
from .views import *
app_name ="Usuarios"

urlpatterns = [
    path("<username>/",ProfileView.as_view(), name="perfil"),
    path("portfolio/<username>",PortfolioView.as_view(), name="portfolio"),
    path('profile/edit', EditProfile, name="editProfile"),

    #Se creó el nuevo path de followers, y de follow y unfollow
    path('profile/followers', followers, name="followers"),    
    path('follow/<str:username>/', follow, name="follow"),
    path('unfollow/<str:username>/', unfollow, name="unfollow"),
]

ConectArte/apps/DM/models.py
from django.db import models
from django.conf import settings
from apps.Usuarios.models import *

import uuid
from django.apps import apps
from django.db.models import Count

User = settings.AUTH_USER_MODEL

class ModelBase(models.Model):
	id = models.UUIDField(default=uuid.uuid4, primary_key=True, db_index=True, editable=False)
	tiempo = models.DateTimeField(auto_now_add=True)
	actualizar = models.DateTimeField(auto_now=True)

	class Meta:
		abstract = True


class CanalMensaje(ModelBase):
	canal   = models.ForeignKey("Canal", on_delete=models.CASCADE)
	usuario = models.ForeignKey(User, on_delete=models.CASCADE)
	texto =  models.TextField()

class CanalUsuario(ModelBase):
	canal  = models.ForeignKey("Canal", null=True, on_delete=models.SET_NULL)
	usuario = models.ForeignKey(User, on_delete=models.CASCADE)


class CanalQuerySet(models.QuerySet):

	def solo_uno(self):
		return self.annotate(num_usuarios=Count("usuarios")).filter(num_usuarios=1)

	def solo_dos(self):
		return self.annotate(num_usuarios= Count("usuarios")).filter(num_usuarios=2)

	def filtrar_por_username(self, username):
		return self.filter(canalusuario__usuario__username=username)


class CanalManager(models.Manager):
	
	def get_queryset(self, *args, **kwargs):
		return CanalQuerySet(self.model, using=self._db)

	def filtrar_ms_por_privado(self, username_a, username_b):
		return self.get_queryset().solo_dos().filtrar_por_username(username_a).filtrar_por_username(username_b)

	def obtener_o_crear_canal_usuario_actual(self, user):
		qs = self.get_queryset().solo_uno().filtrar_por_username(user.username)
		if qs.exists():
			return qs.order_by("tiempo").first, False

		canal_obj = Canal.objects.create()
		CanalUsuario.objects.create(usuario=user, canal=canal_obj)
		return canal_obj, True

	def obtener_o_crear_canal_ms(self, username_a, username_b):
		qs = self.filtrar_ms_por_privado(username_a, username_b)
		if qs.exists():
			return qs.order_by("tiempo").first(), False #obj, created

		obj_canal =Canal.objects.create()
		canal_usuario_a = CanalUsuario(usuario=username_a, canal=obj_canal)
		canal_usuario_b = CanalUsuario(usuario=username_b, canal=obj_canal)
		CanalUsuario.objects.bulk_create([canal_usuario_a, canal_usuario_b])
		return obj_canal, True

class Canal(ModelBase):

	usuarios = models.ManyToManyField(User, blank=True, through=CanalUsuario)
	objects = CanalManager()

ConectArte/templates/components/footer.html
{% load static %}


<footer class="footer">
  
  

  <style>

      #Category_search{

          background-color: white;
          border-radius: 5px;
          margin-left: 25px;
          padding-left: 10px;
          margin-right: 30px;
          padding-top: 5px;
          padding-block-end: 5px;
      }
      
            /* Basic styling */

      [type=checkbox] {
        width: 1rem;
        height: 1rem;
        color: dodgerblue;
        vertical-align: middle;
        -webkit-appearance: none;
        background: none;
        border: 0;
        outline: 0;
        flex-grow: 0;
        border-radius: 50%;
        background-color: #FFFFFF;
        transition: background 300ms;
        cursor: pointer;
      }


      /* Pseudo element for check styling */

      [type=checkbox]::before {
        content: "";
        color: transparent;
        display: block;
        width: inherit;
        height: inherit;
        border-radius: inherit;
        border: 0;
        background-color: transparent;
        background-size: contain;
        box-shadow: inset 0 0 0 1px #CCD3D8;
      }


      /* Checked */

      [type=checkbox]:checked {
        background-color: currentcolor;
      }

      [type=checkbox]:checked::before {
        box-shadow: none;
        background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='24' height='24' viewBox='0 0 24 24'%3E %3Cpath d='M15.88 8.29L10 14.17l-1.88-1.88a.996.996 0 1 0-1.41 1.41l2.59 2.59c.39.39 1.02.39 1.41 0L17.3 9.7a.996.996 0 0 0 0-1.41c-.39-.39-1.03-.39-1.42 0z' fill='%23fff'/%3E %3C/svg%3E");
      }


      /* Disabled */

      [type=checkbox]:disabled {
        background-color: #CCD3D8;
        opacity: 0.84;
        cursor: not-allowed;
      }


      /* IE */

      [type=checkbox]::-ms-check {
        content: "";
        color: transparent;
        display: block;
        width: inherit;
        height: inherit;
        border-radius: inherit;
        border: 0;
        background-color: transparent;
        background-size: contain;
        box-shadow: inset 0 0 0 1px #CCD3D8;
      }

      [type=checkbox]:checked::-ms-check {
        box-shadow: none;
        background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='24' height='24' viewBox='0 0 24 24'%3E %3Cpath d='M15.88 8.29L10 14.17l-1.88-1.88a.996.996 0 1 0-1.41 1.41l2.59 2.59c.39.39 1.02.39 1.41 0L17.3 9.7a.996.996 0 0 0 0-1.41c-.39-.39-1.03-.39-1.42 0z' fill='%23fff'/%3E %3C/svg%3E");
      }

      .filtro_n{
        margin-top: 4px;
        width: 81px;
        height: 30px;
        font-size: 12px;

        border-radius: 3px;

        border-color: #777;
      }

      .filtro_n2{
        width: 80px;
        height: 30px;
        font-size: 12px;
        margin-left: 30px;
        border-radius: 3px;

        border-color: #777;
      }



  </style>


<div class="mt-auto p-6 text-sm text-gray-500 dark:text-dark-txt">

    <a href="/home">Inicio</a>
    <br>
    <span>ConectArte © 2022</span>


</div>

ConectArte/templates/components/navbar.html
{% load static %}

<script src="https://code.iconify.design/iconify-icon/1.0.1/iconify-icon.min.js"></script>
<nav
    class="bg-white dark:bg-dark-second h-max md:h-14 w-full shadow flex flex-col md:flex-row items-center justify-center md:justify-between fixed top-0 z-50 border-b dark:border-dark-third">

    <!-- LEFT NAV -->
    <div class="flex items-center justify-between w-full md:w-max px-4 py-2">
        <a href="/home" class="mr-2 hidden md:inline-block">
            <img src="{% static 'images/logoC.png' %}" alt="ConectArte logo" class="w-24 sm:w-20 lg:w-10 h-auto">
        </a>
        <a href="#" class="inline-block md:hidden">
            <img src="{% static 'images/logoC.png' %}" alt="" class="w-10 h-10">
        </a>
        <div class="flex items-center justify-between space-x-1">
            <a href="#"
                class="inline-flex md:hidden items-center justify-center p-1 rounded-full hover:bg-gray-200 dark:hover:bg-dark-third mx-1"></a>
            <form method="GET" action="{% url 'search:searchProfile' %}">
                <div style="margin-top: 22px;"
                    class=" mt-4 relative bg-gray-100 dark:bg-dark-third px-2 py-2 w-10 h-10 sm:w-11 sm:h-11 lg:h-10 lg:w-10 xl:w-max xl:pl-3 xl:pr-8 rounded-full flex items-center justify-center cursor-pointer">
                    <button type="submit" class='bx bx-search-alt-2 text-xl xl:mr-2 dark:text-dark-txt'></button>
                    <input name="query" value="{{request.GET.query}}" type="text" placeholder="Buscar Usuarios"
                        class="outline-none border-none bg-transparent hidden xl:inline-block">
                </div>
            </form>
            <div class="text-xl grid place-items-center md:hidden bg-gray-200 dark:bg-dark-third rounded-full w-10 h-10 cursor-pointer hover:bg-gray-300 dark:text-dark-txt"
                id="dark-mode-toggle-mb">
                <i class='bx bxs-bell'></i>
            </div>
        </div>
    </div>
    <!-- END LEFT NAV -->

    <!-- MAIN NAV -->
    <ul style="margin-right: 65px;" x-data="{ open: false }" class="flex w-full lg:w-max items-center justify-center">
      <li style="width: 65px; height: 65px;" class="w-1/5 md:w-max text-center">
        <a href="/home" 
                class="w-full text-3xl py-2 px-3 xl:px-12 cursor-pointer text-center inline-block " id="Home">
                <iconify-icon icon="emojione:house"></iconify-icon>
                <h1 style=" font-size: 10px;">Inicio</h1>
            </a>
        </li>

        <li style="width: 65px; height: 65px;" class="w-1/5 md:w-max text-center">
          <a href="/vacantes"
                class="w-full text-3xl py-2 px-3 xl:px-12 cursor-pointer text-center inline-block " id="Vacantes">
                <iconify-icon icon="emojione:performing-arts"></iconify-icon>
                <h1 style=" font-size: 10px;">Vacantes</h1>
            </a>
        </li>

        <li style="width: 65px; height: 65px;" class="w-1/5 md:w-max text-center">
          <a href="{% url 'users:portfolio' user.username %}"
                class="w-full text-3xl py-2 px-3 xl:px-12 cursor-pointer text-center inline-block " id="Portafolio">
                <iconify-icon icon="emojione-v1:briefcase"></iconify-icon>
                <h1 style=" font-size: 10px;">Portafolio</h1>
            </a>
        </li>

        <li style="height: 65px;" class="w-1/5 md:w-max text-center">
          <a href="{% url 'users:followers' %}"
                class="w-full text-3xl py-2 px-3 xl:px-12 cursor-pointer text-center inline-block " id="Red">
                <iconify-icon icon="fluent-emoji-flat:artist-light"></iconify-icon>
                <h1  style=" font-size: 10px; ">Mi red</h1>
                

                </div>
            </a>
        </li>







        



        <!--LEFT Mobile Sidebar-->
        <div @keydown.window.escape="open = false" x-show="open" aria-labelledby="slide-over-title" x-ref="dialog"
            aria-modal="true" class="fixed z-10 inset-0 overflow-auto xl:hidden ">
            <div class="absolute inset-0 overflow-hidden">

                <div x-description="Background overlay, show/hide based on slide-over state." class="absolute inset-0"
                    @click="open = false" aria-hidden="true"></div>

                <div class="fixed inset-y-0 right-0 pl-10 max-w-full flex ">

                    <div x-show="open" @click.away="open = false" class="w-screen max-w-md"
                        x-description="Slide-over panel, show/hide based on slide-over state.">
                        <div
                            class="h-full flex flex-col py-6 bg-white dark:bg-dark-second shadow-xl overflow-y-scroll scrollbar-hide">
                            <div class="px-4 sm:px-6">
                                <div class="flex items-start justify-between">
                                    <h2 class="text-lg font-medium dark:text-gray-500 text-gray-900"
                                        id="slide-over-title">
                                        Menu
                                    </h2>
                                    <div class="ml-3 h-7 flex items-center">
                                        <button
                                            class="bg-white dark:bg-dark-third rounded-md text-gray-400 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
                                            @click="open = false">
                                            <span class="sr-only">Close panel</span>
                                            <svg class="h-6 w-6" x-description="Heroicon name: outline/x"
                                                xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                                stroke="currentColor" aria-hidden="true">
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                                    d="M6 18L18 6M6 6l12 12"></path>
                                            </svg>
                                        </button>
                                    </div>
                                </div>
                            </div>

                            <div class="mt-6 relative flex-1 px-4 sm:px-6">
                                <!-- Replace with your content -->

                                <!--Menu Items-->
                                {% include 'components/sidebars/leftBar/items.html' %}


                                {% include 'components/footer.html' %}

                                <!-- /End replace -->
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>

    </ul>
    <!-- END MAIN NAV -->



    <!-- RIGHT NAV -->
    <ul class="hidden md:flex mx-4 items-center justify-center">

        <li class="h-full xl:flex">
        </li>
        
        <li>
            
            <div x-data="{open:false}">
                <div @click="open=true"
                class="text-xl grid place-items-center bg-gray-200 dark:bg-dark-third dark:text-dark-txt rounded-full mx-1 p-3 cursor-pointer hover:bg-gray-300 relative">
                <i class='bx bx-message-dots'></i>
                <span
                    class="text-xs absolute top-0 right-0 bg-red-500 text-white font-semibold rounded-full px-1 text-center"></span>
                </div>
                <div x-show="open" @click.away="open=false"
                    class="origin-top-right absolute right-0 mt-2 w-56 rounded-md shadow-lg dark:bg-dark-second bg-white ring-1 ring-black ring-opacity-5 focus:outline-none"
                    role="menu" aria-orientation="vertical" aria-labelledby="menu-button" tabindex="-1">
                    <div class="py-1" role="none">
  
                        {% block contenedor %}


                            <h2 style="text-align: center; font-weight: 600;" class="modal-title" id="exampleModalLabel">Bienvenido a tus mensajes
                            {{user}}</h2>

                            {% for inbox in inbox %}
                            <div class="div_inbox">


                            {% for second_user in inbox.canalusuario_set.all %}

                            {% if second_user.usuario == request.user %}

                            {% else %}

                            <a href="{% url 'dm:detailms' second_user.usuario.username %}">
                                <p>
                                <h2 style="text-align: center; font-weight: 600;color: rgb(22, 148, 232);" class="modal-title"
                                    id="exampleModalLabel">{{second_user.usuario}}</h2>
                                </p>
                                <small>
                                Tienes ({{inbox.canalmensaje_set.count}}) Mensajes
                                </small>
                            </a>

                            {% endif %}

                            {% endfor %}

                            {% if inbox.canalmensaje_set.count != 0 %}
                            <div class="div_ms_inbox">

                                {% with ultimo_mensaje=inbox.canalmensaje_set.last %}

                                <p>
                                <h2 style="text-align: center; font-weight: 650;font-size: 12px;" class="modal-title" id="exampleModalLabel">
                                Mensaje: {{ultimo_mensaje.texto}}</h2>
                                </p>

                                {% endwith %}
                            </div>
                            {% else %}
                            <p>
                            <h2 style="text-align: center; font-weight: 650;font-size: 12px;" class="modal-title" id="exampleModalLabel">No hay
                                mensajes en el chat</h2>
                            </p>
                            {% endif %}



                            </div>
                            {% empty %}

                            <div class="div_inbox">
                            <h2 style="text-align: center; font-weight: 600;font-size: 15px;" class="modal-title" id="exampleModalLabel">No tienes
                                ningún mensaje</h2>
                            </div>


                            {% endfor %}


                            <style>
                            .div_inbox {
                                width: 100%;
                                margin: 10px auto;
                                background: #fff;
                                border-radius: 10px;
                                border: 1px solid #e6e6e6;
                                padding: 10px;
                                text-align: center;
                            }
                            </style>

                            {% endblock %}
                    </div>
                </div>
            </div>
        </li>


        <li>
            <div x-data="{open:false}">
                <div @click="open=true"
                    class="text-xl grid place-items-center dark:bg-dark-second bg-gray-200 dark:bg-dark-third dark:text-dark-txt rounded-full mx-1 p-3 cursor-pointer hover:bg-gray-300 relative">
                    <i class='bx bxs-bell'></i>
                    <span
                        class="text-xs absolute top-0 right-0 bg-red-500 text-white font-semibold rounded-full px-1 text-center"></span>
                </div>
                <div x-show="open" @click.away="open=false"
                    class="origin-top-right absolute right-0 mt-2 w-56 rounded-md shadow-lg dark:bg-dark-second bg-white ring-1 ring-black ring-opacity-5 focus:outline-none"
                    role="menu" aria-orientation="vertical" aria-labelledby="menu-button" tabindex="-1">
                    <div class="py-1" role="none">
  
                        {% if user.is_authenticated %}
                        <a href="{% url 'account_logout' %}"
                            class="text-gray-700 dark:text-dark-txt block px-4 py-2 text-sm" role="menuitem"
                            tabindex="-1" id="menu-item-2">Cerrar Sesion</a>
                        {% endif %}
                    </div>
                </div>
            </div>

        </li>
    </ul>
    <!-- END RIGHT NAV -->


</nav>