ConectArte/ConectArte/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib import admin
from django.urls import include, path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from apps.vacantes.views import *
from .views import HomeView, home
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', HomeView.as_view(), name = 'home'),
    path('', home),
    path('accounts/', include('allauth.urls')),
    path('users/', include('apps.Usuarios.urls', namespace ="users")),
    path('search/', include('apps.Buscador.urls', namespace='search')),
    path('publicacion/', include('apps.publicaciones.urls', namespace='publicacion')),
    path('vacantes/', VacanteView.as_view(), name="vacante"),
    path('dm/', include('apps.DM.urls', namespace='dm')),
    
]

urlpatterns += staticfiles_urlpatterns()
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ConectArte/apps/Usuarios/urls.py
from django.urls import path 
from .views import *
app_name ="Usuarios"

urlpatterns = [
    path("<username>/",ProfileView.as_view(), name="perfil"),
    path("portfolio/<username>",PortfolioView.as_view(), name="portfolio"),
    path('profile/edit', EditProfile, name="editProfile"),

    #Se creó el nuevo path de followers, y de follow y unfollow
    path('profile/followers', followers, name="followers"),    
    path('follow/<str:username>/', follow, name="follow"),
    path('unfollow/<str:username>/', unfollow, name="unfollow"),
]

ConectArte/templates/users/editProfile.html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
  integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
  integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
  integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
  integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>






{% extends 'base.html' %}
{% load static %}

{% block navbar %}
{% include 'components/navbar.html' %}
{% endblock navbar %}


{% block left_sidebar %}
{% include 'components/sidebars/leftBar/sidebar.html' %}

{% endblock left_sidebar %}



{% block title %}{{user.username}} Edit Profile{% endblock title %}



{% block content %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

<form class="form-horizontal dark:text-dark-txt" method="post" enctype="multipart/form-data">
  {% csrf_token %}

  <div style="box-shadow: 0px 0px 0.5px 0.5px  #d1d1d1; border: 1px solid #e0dfdc;"
    class="min-h-screen bg-gray-50 flex flex-col justify-center py-12 sm:px-6 lg:px-8">
    <div class="sm:mx-auto sm:w-full sm:max-w-md">

    </div>

    <div class="mt-8  sm:max-w-md">
      <div style=" height: 590px; border-radius: 10px; width: 95%; margin-left: 2%;"
        class="bg-white py-8 px-4 shadow sm:rounded-lg sm:px-10">
        <div>

          <div class="mx-auto"
            style=" vertical-align: middle; border: rgb(223, 216, 216) 5px solid;  position: relative; width: 120px; height: 120px; overflow: hidden; border-radius: 50%;">
            {% for img in perfil.usuario.fotoPerfil.all %}
            <img style=" width: 100%; height: 100%; " class="mx-auto" src="{{img.imagen.url}}" alt="">
            {% endfor %}

          </div>

          <div class="mt-4">
            <label for="profile_Image" class="block text-sm font-medium dark:text-dark-txt text-gray-700">
              Foto de perfil
            </label>
            {{form.fotoPerfil}}
          </div>

          <div class="mt-4">
            <label for="first_name" class="block text-sm font-medium dark:text-dark-txt text-gray-700">
              Nombre:
            </label>
            {{form.first_name}}
          </div>

          <div class="mt-4">
            <label for="last_name" class="block text-sm font-medium dark:text-dark-txt text-gray-700">
              Apellido:
            </label>
            {{form.last_name}}
          </div>

          <div class="mt-4">
            <label for="first_name" class="block text-sm font-medium dark:text-dark-txt text-gray-700">
              Telefono:
            </label>
            {{form.NumeroTelefono}}
          </div>


          <div class="mt-4">
            <label for="url" class="block text-sm font-medium dark:text-dark-txt text-gray-700">
              Pagina web:
            </label>
            {{form.url}}
          </div>

        </div>
      </div>
    </div>

    <div class="mt-8  sm:max-w-md">
      <div style=" height: 240px; border-radius: 10px; width: 95%; margin-left: 2%;"
        class="bg-white py-8 px-4 shadow sm:rounded-lg sm:px-10">
        <h1 style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;  font-weight: 500;
        margin-top: 2%; color: black; font-size: 30px;">Sobre mi</h1>
        <div class="mt-4">
          <label for="Descripcion" class="block text-sm font-medium dark:text-dark-txt text-gray-700">
          </label>
          {{form.Descripcion}}
        </div>
      </div>
    </div>
    <!-- 
    <div class="form-group" rows="6">
      Elige una categoria para la vacante
      {{form.Categoria}}
    </div>  -->

    <div class="mt-8  sm:max-w-md">
      <div style=" height: 240px; border-radius: 10px; width: 95%; margin-left: 2%;"
        class="bg-white py-8 px-4 shadow sm:rounded-lg sm:px-10">
        <h1 style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;  font-weight: 500;
        margin-top: 2%; color: black; font-size: 30px;">Experiencia</h1>
        <div class="mt-4">
          <label for="Experiencia" class="block text-sm font-medium dark:text-dark-txt text-gray-700">
          </label>
          {{form.Experiencia}}


        </div>

      </div>
    </div>

    <div class="mt-8  sm:max-w-md">
      <div style=" height: 240px; border-radius: 10px; width: 95%; margin-left: 2%;"
        class="bg-white py-8 px-4 shadow sm:rounded-lg sm:px-10">
        <h1 style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;  font-weight: 500;
        margin-top: 2%; color: black; font-size: 30px;">Educación</h1>
        <h1 style="font-size: 20px; color: rgb(99, 99, 100);">{{perfil.Educacion}}</h1>
        <div class="mt-4">
          <label for="Educacion" class="block text-sm font-medium dark:text-dark-txt text-gray-700">
          </label>
          {{form.Educacion}}
        </div>

      </div>
    </div>


    <div class="mt-8  sm:max-w-md">
      <div style=" height: 240px; border-radius: 10px; width: 95%; margin-left: 2%;"
        class="bg-white py-8 px-4 shadow sm:rounded-lg sm:px-10">
        <h1 style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;  font-weight: 500;
        margin-top: 2%; color: black; font-size: 30px;">Intereses</h1>
        <h1 style="font-size: 20px; color: rgb(99, 99, 100);">{{perfil.Intereses}}</h1>
        <div class="mt-4">
          <label for="Intereses" class="block text-sm font-medium dark:text-dark-txt text-gray-700">
          </label>
          {{form.Intereses}}
        </div>

      </div>
    </div>
    <div class="mt-8  sm:max-w-md">

      <button type="submit" class="btn btn-primary btn-lg btn-block">
        Editar
      </button>
      <a href="{% url 'users:perfil' username=user.username %}"
        class="mt-4 inline-flex items-center px-2.5 py-1.5 border border-transparent text-xs font-medium rounded dark:text-dark-txt text-indigo-700 dark:bg-dark-second bg-indigo-100 dark:hover:bg-dark-third hover:bg-indigo-200 focus:outline-none focus:ring-2 focus:ring-offset-2 dark:focus:ring-dark-third focus:ring-indigo-500">
        volver al perfil </a>


    </div>

  </div>

</form>

{% endblock content %}

ConectArte/templates/users/followers.html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
  integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
  integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
  integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
  integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>





{% extends 'base.html' %}

{% load static %}
{% block navbar %}
<style>
    #Red{
      border-bottom: 4px #3c84f4 solid; margin-bottom: 40px; position: relative;
    }
  </style>
{% include 'components/navbar.html' %}
{% endblock navbar %}


{% block left_sidebar %}

{% include 'components/sidebars/leftBar/sidebar.html' %}

{% endblock left_sidebar %}

{% block content %}


<div style="box-shadow: 0px 0px 0.5px 0.5px  #d1d1d1; border: 1px solid #e0dfdc;" class="min-h-screen bg-gray-50 flex flex-col justify-center py-12 sm:px-6 lg:px-8">
  <div  class="sm:mx-auto sm:w-full sm:max-w-md">

  </div>
  <div  class="mt-8  sm:max-w-md">
    <div style=" border-radius: 10px; width: 95%; margin-left: 2%;" class="bg-white py-8 px-4 shadow sm:rounded-lg sm:px-10">

        <i class='bx bx-user-plus'style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;  font-weight: 500;
        margin-top: 2%; color: black; font-size: 30px;"></i>
        <span style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;  font-weight: 500;
        margin-top: 2%; color: black; font-size: 30px;">Usuarios a los que sigues:</span>    <br>


        <ul>
        {% for i in profreq.following %}     
        <li>          </style>
          <div class="hodd" style="margin-top: 20px;">
  
            <div id = "results" style="display: flex; border-radius: 5px; width: 100%; margin-top: 20px; height: 13%;"> 
                
              </a>
              <spam 
              style=" font-size: 15px; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;  font-weight: 500;margin-top: 12px; margin-left: 15px;">{{i}}</spam>
      
              <spam 
              style=" font-size: 10px; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;  font-weight: 500;margin-top: 38px; margin-left: -55px; color: grey;">Bogotá D.C, Colombia<br>
            </div>
          </a>
          </div> </li>
        {% endfor %}
        </ul>


        
    </div>
  </div>

</div>
{% endblock content %}

ConectArte/templates/users/perfilUsuario.html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
  integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
  integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
  integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
  integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>






{% extends 'base.html' %}
{% load static %}

{% block navbar %}
{% include 'components/navbar.html' %}
{% endblock navbar %}


{% block left_sidebar %}
{% include 'components/sidebars/leftBar/sidebar.html' %}

{% endblock left_sidebar %}



{% block content %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

<div style="box-shadow: 0px 0px 0.5px 0.5px  #d1d1d1; border: 1px solid #e0dfdc;"
  class="min-h-screen bg-gray-50 flex flex-col justify-center py-12 sm:px-6 lg:px-8">
  <div class="sm:mx-auto sm:w-full sm:max-w-md">

  </div>

  <div class="mt-8  sm:max-w-md">
    <div style=" border-radius: 10px; width: 95%; margin-left: 2%;"
      class="bg-white py-8 px-4 shadow sm:rounded-lg sm:px-10">
      <div>
          
        <div class="mx-auto" style=" vertical-align: middle; border: rgb(223, 216, 216) 5px solid;  position: relative; width: 120px; height: 120px; overflow: hidden; border-radius: 50%;">
          {% for img in perfil.usuario.fotoPerfil.all %}
            <img style=" width: 100%; height: 100%; " class="mx-auto" src="{{img.imagen.url}}"  alt="">
          {% endfor %}

        </div>

        <h5 style="font-size: 15px 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;  font-weight: 500;
            margin-top: 2%; color: black; font-size: 30px;">{{user.first_name}} {{user.last_name}}</h5>
        <h1 style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;  font-weight: 500;
            margin-top: 2%; color: black; font-size: px;">{{perfil.usuario.username}}</h1>



            <!--Botones de follow y unfollow, usan if para comprobar si el usuario sigue o no a esa cuenta-->

            {%if request.user.is_authenticated%}  
              {%if request.user.username != perfil.usuario.username %}
                  {%if perfil.usuario.username not in profreq.following%}
                    <button class="Followers"><a  href="{% url 'users:follow' perfil.usuario %}">Seguir</a></button>
                  {%else%}
                    <button class="Followers"><a  href="{% url 'users:unfollow' perfil.usuario %}">Siguiendo</a></button>
                  {%endif%}
              {%endif%}
            {%endif%}

            
            <style>

              .Followers{
                margin-left: 70%;
                margin-top: -33px; 
                
                font-weight: 500; background-color: rgb(153, 181, 198); 
                color: white;
                text-align: center; 
                border-radius: 10px; 
                height: 30px; 
                width: 30%;
              }

              .Followers:hover{ 
                  transition: 0.6s;
                  background-color: rgb(79, 79, 208);
              }
            </style>

           
            
            <h1 style="font-size: 20px; color: rgb(164, 165, 167);">Bogotá D.C, Colombia</h1>
            <h1 style="font-size: 20px; color: rgb(164, 165, 167);">Telefono: {{perfil.NumeroTelefono}}</h1>
            <h1 style="font-size: 20px; color: rgb(164, 165, 167);">Fecha de unión: {{user.date_joined}}</h1>
            <h1 href="" style="font-size: 20px; color: rgb(164, 165, 167);">Mas sobre mi: <a style=" text-decoration-line: underline;
              ;color: rgb(0, 85, 255);" href="http://{{perfil.url}}">{{perfil.url}}</a></h1>





      </div>
    </div>
  </div>

  <div class="mt-8  sm:max-w-md">
    <div style=" border-radius: 10px; width: 95%; margin-left: 2%;"
      class="bg-white py-8 px-4 shadow sm:rounded-lg sm:px-10">
      <h1 style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;  font-weight: 500;
        margin-top: 2%; color: black; font-size: 30px;">Sobre mi</h1>
      <h1 style="font-size: 20px; color: rgb(99, 99, 100);">{{perfil.Descripcion}}</h1>


    </div>
  </div>

  <div class="mt-8  sm:max-w-md">
    <div style=" border-radius: 10px; width: 95%; margin-left: 2%;"
      class="bg-white py-8 px-4 shadow sm:rounded-lg sm:px-10">
      <h1 style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;  font-weight: 500;
        margin-top: 2%; color: black; font-size: 30px;">Experiencia</h1>
      <h1 style="font-size: 20px; color: rgb(99, 99, 100);">{{perfil.Experiencia}}</h1>


    </div>
  </div>

  <div class="mt-8  sm:max-w-md">
    <div style=" border-radius: 10px; width: 95%; margin-left: 2%;"
      class="bg-white py-8 px-4 shadow sm:rounded-lg sm:px-10">
      <h1 style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;  font-weight: 500;
        margin-top: 2%; color: black; font-size: 30px;">Educación</h1>
      <h1 style="font-size: 20px; color: rgb(99, 99, 100);">{{perfil.Educacion}}</h1>


    </div>
  </div>


  <div class="mt-8  sm:max-w-md">
    <div style=" border-radius: 10px; width: 95%; margin-left: 2%;"
      class="bg-white py-8 px-4 shadow sm:rounded-lg sm:px-10">
      <h1 style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;  font-weight: 500;
        margin-top: 2%; color: black; font-size: 30px;">Intereses</h1>
      <h1 style="font-size: 20px; color: rgb(99, 99, 100);">{{perfil.Intereses}}</h1>


    </div>
  </div>
  <div>
    {%if request.user.username != perfil.usuario.username %}
    <a href="{% url 'users:portfolio' perfil.usuario.username %}" class="flex items-center space-x-2 p-2 hover:bg-gray-200 rounded-lg transition-all dark:text-dark-txt dark:hover:bg-dark-third">
      <i class='bx bx-right-arrow-alt'></i>
      <span class="font-semibold">Visita mi portafolio</span>
    </a>
    {%endif %}
    {%if request.user.username == perfil.usuario.username %}
    <a href="{% url 'users:editProfile' %}" class="flex items-center space-x-2 p-2 hover:bg-gray-200 rounded-lg transition-all dark:text-dark-txt dark:hover:bg-dark-third">
      <i class='bx bx-right-arrow-alt'></i>
      <span class="font-semibold">Editar perfil</span>
    </a>
    {%endif %}

    <a href="{% url 'account_login' %}"
      class="flex items-center space-x-2 p-2 hover:bg-gray-200 rounded-lg transition-all dark:text-dark-txt dark:hover:bg-dark-third">
      <i class='bx bx-left-arrow-alt'></i>
      <span class="font-semibold">Regresar al inicio</span>
    </a>
    
  </div>
  <div>

  </div>

</div>
{% endblock content %}


{% block right_sidebar %}
{% endblock right_sidebar %}



{% block footer %}
{% endblock footer %}

{% block javascript %}{% endblock javascript %}